# Generated by Django 5.1.2 on 2024-10-14 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='name',
            field=models.CharField(default=7872, max_length=100, unique=True),
            preserve_default=False,
        ),
    ]
