# Generated by Django 5.1.2 on 2024-10-14 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0003_remove_seat_seat_number_seat_seat_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='booked_at',
            new_name='booking_time',
        ),
    ]
